### ISSUE TITLE
微信小程序增加 getPhoneNumber 方法

### ISSUE THREAD

**Issue by rockliuxn** [baaxl9vh/nest-wechat#1]
@baaxl9vh  你好！ 

小程序获取手机号也是常用功能，敬请添加，感谢！☕️

[API:  getPhoneNumber](https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/phonenumber/phonenumber.getPhoneNumber.html)

**Comment by baaxl9vh** [comment]
不好意思，回复晚了，已经加上了。

Closes #
