### ISSUE TITLE
使用微信公众平台测试号调试时，事件推送为明文xml的问题

### ISSUE THREAD

**Issue by limars874** [baaxl9vh/nest-wechat#19]
好像您这边的代码默认都是会推送aes加密的消息，所以都会走解密的代码，现在用测试号调试的时候，无法配置加密信息，所以事件推送全都是明文xml，然后您这边的代码就反而解析不出来。能否可以考虑明文的情况。

**Comment by baaxl9vh** [comment]
1、明文消息只需要验证，可以用checkSignatureExpress方法验证。
 2、加密消息测试可以在[微信开放平台调试工具-消息推送测试](https://developers.weixin.qq.com/apiExplorer?type=messagePush)测试，[说明文档](https://baaxl9vh.github.io/nest-wechat/#/README?id=消息推送测试)
