### ISSUE TITLE
多小程序支持

### ISSUE THREAD

**Issue by Bluebang** [baaxl9vh/nest-wechat#2]
Hi，

可否增加对多小程序的支持？

**Comment by baaxl9vh** [comment]
可以，我抽空补一下。

[code2session](https://github.com/baaxl9vh/nest-wechat/blob/da5ef1f99ccfc15012c1628bff00e8fbf88e474b/lib/miniprogram.service.ts#L24)小程序登录接口支持多个小程序

```typescript
wechat.mp.code2Session('wx/login/code', 'wx/appid', 'wx/secret')；
```

**Comment by baaxl9vh** [comment]
wechat service封装的方法可传入appid和secret，支持多公众号多小程序情景

commit: d91d1f045628734202ef85f829463c34a1968ff9

**Comment by Bluebang** [comment]
good job！
