### ISSUE TITLE
小程序中的access_token过期后，没有返回错误码

### ISSUE THREAD

**Issue by myadmin** [baaxl9vh/nest-wechat#6]
hi，作者你好，在开发中我们将access_token保存在redis中，当其它地方用到了该access_token后，redis中保存的access_token就过期了，当继续调用生成微信二维码的接口时，由于access_token过期了，导致生成二维码失败，官方的接口中给了错误时的返回数据，不过我看你这边好像是没有将错误时相关的数据暴露出来。
![image](https://user-images.githubusercontent.com/6794499/221770141-8c617fb8-49da-43f5-badc-3b6e1f78c6b8.png)
![image](https://user-images.githubusercontent.com/6794499/221770019-f4ffb6ee-a846-4402-a2d1-8c3c7597a022.png)
麻烦更新一下，谢谢！

**Comment by baaxl9vh** [comment]
Hi，有Demo代码么？

你看下我的理解对不对，你是希望当access_token过期时，得到调用MiniProgramService生成小程序码接口时微信的返回值吗？

access_token维护逻辑需要你自己实现，接口其实只是一个简单的HTTP请求封装，使用的HTTP Client是axios，接口会直接return axios.[method]，微信返回什么，封装的接口只是简单粗暴直接返回。

可以参考测试代码：https://github.com/baaxl9vh/nest-wechat/blob/cc62a01fcfd8deee8c5d0a1571db868ab0940160/lib/miniprogram.service.spec.ts#L52

**Comment by myadmin** [comment]
@baaxl9vh 我在本地测试，传入一个错误的access_token后，生成小程序的接口中是在headers里面返回了40001的错误码，如下图所示：
![image](https://user-images.githubusercontent.com/6794499/222607463-cc494e4c-e84d-4992-b223-fb06f54dd92a.png)
感谢你的回复。
